# Generated by Django 4.2.4 on 2023-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
