# Generated by Django 4.2.4 on 2023-09-17 06:57

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(
                null=True, validators=[user.validators.validate_date_of_birth]
            ),
        ),
    ]
