# Generated by Django 4.2.4 on 2023-09-17 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
    ]
