# Generated by Django 4.2.4 on 2023-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_userprofile_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
