# Generated by Django 4.2.4 on 2023-10-13 09:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_remove_task_id_task_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
