# Generated by Django 4.2.4 on 2023-10-24 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_alter_options_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Options",
            new_name="Option",
        ),
    ]
