# Generated by Django 4.2.4 on 2023-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0007_rename_options_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="permalink_id",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
